-- Synthetic offline fixture reconstructed from the supplied six-table baseline.
-- Only the disposable test runner loads this file. No production rows or credentials.
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE SCHEMA auth;
CREATE TABLE auth.users(id uuid PRIMARY KEY);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
  $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
GRANT USAGE ON SCHEMA public, auth TO anon, authenticated;
GRANT EXECUTE ON FUNCTION auth.uid() TO anon, authenticated;
CREATE FUNCTION public.uuid_generate_v4() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$;
CREATE TABLE public.admin_profiles ("id" uuid NOT NULL, "email" text NOT NULL, "full_name" text, "is_super_admin" boolean DEFAULT false, "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL);
CREATE TABLE public.audit_log ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "action" text NOT NULL, "details" jsonb, "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()), "user_id" uuid, "user_email" text, "ip_address" text);
CREATE TABLE public.carriers ("id" uuid DEFAULT uuid_generate_v4() NOT NULL, "name" text NOT NULL, "logo_url" text, "supported_countries" text[] DEFAULT ARRAY[]::text[]);
CREATE TABLE public.price_change_notifications ("id" uuid DEFAULT uuid_generate_v4() NOT NULL, "carrier_id" uuid, "service_id" uuid, "old_price" numeric, "new_price" numeric, "created_at" timestamp with time zone DEFAULT now(), "read" boolean DEFAULT false);
CREATE TABLE public.products ("id" uuid DEFAULT uuid_generate_v4() NOT NULL, "code" text DEFAULT gen_random_uuid() NOT NULL, "name" text NOT NULL, "items_per_box" integer NOT NULL, "image_url" text NOT NULL, "items_per_pallet" integer NOT NULL, "parcel_disabled" boolean DEFAULT false, "pallet_disabled" boolean DEFAULT false, "multiple_boxes" boolean DEFAULT false, "boxes_per_item" integer DEFAULT 1);
CREATE TABLE public.services ("id" uuid DEFAULT uuid_generate_v4() NOT NULL, "name" text NOT NULL, "shipment_type" text NOT NULL, "price_per_unit" integer NOT NULL, "carrier_id" uuid);
ALTER TABLE public.admin_profiles ADD CONSTRAINT admin_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.carriers ADD CONSTRAINT carriers_pkey PRIMARY KEY (id);
ALTER TABLE public.price_change_notifications ADD CONSTRAINT price_change_notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.products ADD CONSTRAINT products_code_key UNIQUE (code);
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE public.services ADD CONSTRAINT services_pkey PRIMARY KEY (id);
ALTER TABLE public.services ADD CONSTRAINT services_shipment_type_check CHECK (shipment_type = ANY (ARRAY['balik'::text, 'paleta'::text]));
ALTER TABLE public.admin_profiles ADD CONSTRAINT admin_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.price_change_notifications ADD CONSTRAINT price_change_notifications_carrier_id_fkey FOREIGN KEY (carrier_id) REFERENCES carriers(id);
ALTER TABLE public.price_change_notifications ADD CONSTRAINT price_change_notifications_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id);
ALTER TABLE public.services ADD CONSTRAINT services_carrier_id_fkey FOREIGN KEY (carrier_id) REFERENCES carriers(id) ON DELETE CASCADE;
ALTER TABLE public.admin_profiles ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.admin_profiles TO anon, authenticated;
CREATE POLICY "allow_admin_access" ON public.admin_profiles FOR ALL TO authenticated USING ((auth.uid() = '00000000-0000-0000-0000-000000000003'::uuid));
CREATE POLICY "allow_read_for_authenticated" ON public.admin_profiles FOR SELECT TO authenticated USING (true);
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.audit_log TO anon, authenticated;
ALTER TABLE public.carriers ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.carriers TO anon, authenticated;
CREATE POLICY "Allow public read" ON public.carriers FOR SELECT TO anon, authenticated USING (true);
ALTER TABLE public.price_change_notifications ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.price_change_notifications TO anon, authenticated;
CREATE POLICY "Allow public read" ON public.price_change_notifications FOR SELECT TO anon USING (true);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.products TO anon, authenticated;
CREATE POLICY "Allow public read" ON public.products FOR SELECT TO anon USING (true);
CREATE POLICY "Enable read access for all users" ON public.products FOR SELECT TO public USING (true);
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.services TO anon, authenticated;
CREATE POLICY "Allow public read" ON public.services FOR SELECT TO anon, authenticated USING (true);

-- User-described production behavior, not a claim to have exported the exact body.
CREATE FUNCTION public.log_price_changes() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE last_change timestamptz;
BEGIN
  SELECT created_at INTO last_change FROM public.price_change_notifications
    WHERE service_id = NEW.id ORDER BY created_at DESC LIMIT 1;
  IF OLD.price_per_unit <> NEW.price_per_unit
    AND (last_change IS NULL OR now() - last_change > interval '5 seconds') THEN
    INSERT INTO public.price_change_notifications(carrier_id, service_id, old_price, new_price)
      VALUES(NEW.carrier_id, NEW.id, OLD.price_per_unit, NEW.price_per_unit);
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER track_price_changes AFTER UPDATE ON public.services
  FOR EACH ROW EXECUTE FUNCTION public.log_price_changes();
INSERT INTO auth.users VALUES
  ('00000000-0000-0000-0000-000000000001'),
  ('00000000-0000-0000-0000-000000000002');
INSERT INTO public.admin_profiles(id,email,is_super_admin) VALUES
  ('00000000-0000-0000-0000-000000000001','admin@example.invalid',true),
  ('00000000-0000-0000-0000-000000000002','reader@example.invalid',false);
